package ir.ord.application.dto.protoes;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreditProto.proto

public final class CreditProto {
  private CreditProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreditOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Credit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>double amount = 2;</code>
     */
    double getAmount();

    /**
     * <code>int64 payDate = 3;</code>
     */
    long getPayDate();

    /**
     * <code>string orderId = 4;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>string orderId = 4;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>.BankInfo bankInfoDto = 5;</code>
     */
    boolean hasBankInfoDto();
    /**
     * <code>.BankInfo bankInfoDto = 5;</code>
     */
    CreditProto.BankInfo getBankInfoDto();
    /**
     * <code>.BankInfo bankInfoDto = 5;</code>
     */
    CreditProto.BankInfoOrBuilder getBankInfoDtoOrBuilder();

    /**
     * <code>string description = 6;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 6;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>double balance = 7;</code>
     */
    double getBalance();

    /**
     * <code>int32 payType = 8;</code>
     */
    int getPayType();
  }
  /**
   * Protobuf type {@code Credit}
   */
  public  static final class Credit extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Credit)
      CreditOrBuilder {
    // Use Credit.newBuilder() to construct.
    private Credit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Credit() {
      id_ = "";
      amount_ = 0D;
      payDate_ = 0L;
      orderId_ = "";
      description_ = "";
      balance_ = 0D;
      payType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Credit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 17: {

              amount_ = input.readDouble();
              break;
            }
            case 24: {

              payDate_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 42: {
              CreditProto.BankInfo.Builder subBuilder = null;
              if (bankInfoDto_ != null) {
                subBuilder = bankInfoDto_.toBuilder();
              }
              bankInfoDto_ = input.readMessage(CreditProto.BankInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bankInfoDto_);
                bankInfoDto_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 57: {

              balance_ = input.readDouble();
              break;
            }
            case 64: {

              payType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CreditProto.internal_static_Credit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CreditProto.internal_static_Credit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CreditProto.Credit.class, CreditProto.Credit.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private double amount_;
    /**
     * <code>double amount = 2;</code>
     */
    public double getAmount() {
      return amount_;
    }

    public static final int PAYDATE_FIELD_NUMBER = 3;
    private long payDate_;
    /**
     * <code>int64 payDate = 3;</code>
     */
    public long getPayDate() {
      return payDate_;
    }

    public static final int ORDERID_FIELD_NUMBER = 4;
    private volatile java.lang.Object orderId_;
    /**
     * <code>string orderId = 4;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>string orderId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BANKINFODTO_FIELD_NUMBER = 5;
    private CreditProto.BankInfo bankInfoDto_;
    /**
     * <code>.BankInfo bankInfoDto = 5;</code>
     */
    public boolean hasBankInfoDto() {
      return bankInfoDto_ != null;
    }
    /**
     * <code>.BankInfo bankInfoDto = 5;</code>
     */
    public CreditProto.BankInfo getBankInfoDto() {
      return bankInfoDto_ == null ? CreditProto.BankInfo.getDefaultInstance() : bankInfoDto_;
    }
    /**
     * <code>.BankInfo bankInfoDto = 5;</code>
     */
    public CreditProto.BankInfoOrBuilder getBankInfoDtoOrBuilder() {
      return getBankInfoDto();
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 6;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BALANCE_FIELD_NUMBER = 7;
    private double balance_;
    /**
     * <code>double balance = 7;</code>
     */
    public double getBalance() {
      return balance_;
    }

    public static final int PAYTYPE_FIELD_NUMBER = 8;
    private int payType_;
    /**
     * <code>int32 payType = 8;</code>
     */
    public int getPayType() {
      return payType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (amount_ != 0D) {
        output.writeDouble(2, amount_);
      }
      if (payDate_ != 0L) {
        output.writeInt64(3, payDate_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, orderId_);
      }
      if (bankInfoDto_ != null) {
        output.writeMessage(5, getBankInfoDto());
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, description_);
      }
      if (balance_ != 0D) {
        output.writeDouble(7, balance_);
      }
      if (payType_ != 0) {
        output.writeInt32(8, payType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, amount_);
      }
      if (payDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, payDate_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, orderId_);
      }
      if (bankInfoDto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getBankInfoDto());
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, description_);
      }
      if (balance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, balance_);
      }
      if (payType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, payType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CreditProto.Credit)) {
        return super.equals(obj);
      }
      CreditProto.Credit other = (CreditProto.Credit) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (
          java.lang.Double.doubleToLongBits(getAmount())
          == java.lang.Double.doubleToLongBits(
              other.getAmount()));
      result = result && (getPayDate()
          == other.getPayDate());
      result = result && getOrderId()
          .equals(other.getOrderId());
      result = result && (hasBankInfoDto() == other.hasBankInfoDto());
      if (hasBankInfoDto()) {
        result = result && getBankInfoDto()
            .equals(other.getBankInfoDto());
      }
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (
          java.lang.Double.doubleToLongBits(getBalance())
          == java.lang.Double.doubleToLongBits(
              other.getBalance()));
      result = result && (getPayType()
          == other.getPayType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + PAYDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPayDate());
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      if (hasBankInfoDto()) {
        hash = (37 * hash) + BANKINFODTO_FIELD_NUMBER;
        hash = (53 * hash) + getBankInfoDto().hashCode();
      }
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBalance()));
      hash = (37 * hash) + PAYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPayType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CreditProto.Credit parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.Credit parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.Credit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.Credit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.Credit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.Credit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.Credit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CreditProto.Credit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CreditProto.Credit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CreditProto.Credit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CreditProto.Credit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CreditProto.Credit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CreditProto.Credit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Credit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Credit)
        CreditProto.CreditOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CreditProto.internal_static_Credit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CreditProto.internal_static_Credit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CreditProto.Credit.class, CreditProto.Credit.Builder.class);
      }

      // Construct using CreditProto.Credit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        amount_ = 0D;

        payDate_ = 0L;

        orderId_ = "";

        if (bankInfoDtoBuilder_ == null) {
          bankInfoDto_ = null;
        } else {
          bankInfoDto_ = null;
          bankInfoDtoBuilder_ = null;
        }
        description_ = "";

        balance_ = 0D;

        payType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CreditProto.internal_static_Credit_descriptor;
      }

      public CreditProto.Credit getDefaultInstanceForType() {
        return CreditProto.Credit.getDefaultInstance();
      }

      public CreditProto.Credit build() {
        CreditProto.Credit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CreditProto.Credit buildPartial() {
        CreditProto.Credit result = new CreditProto.Credit(this);
        result.id_ = id_;
        result.amount_ = amount_;
        result.payDate_ = payDate_;
        result.orderId_ = orderId_;
        if (bankInfoDtoBuilder_ == null) {
          result.bankInfoDto_ = bankInfoDto_;
        } else {
          result.bankInfoDto_ = bankInfoDtoBuilder_.build();
        }
        result.description_ = description_;
        result.balance_ = balance_;
        result.payType_ = payType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CreditProto.Credit) {
          return mergeFrom((CreditProto.Credit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CreditProto.Credit other) {
        if (other == CreditProto.Credit.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (other.getPayDate() != 0L) {
          setPayDate(other.getPayDate());
        }
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (other.hasBankInfoDto()) {
          mergeBankInfoDto(other.getBankInfoDto());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getBalance() != 0D) {
          setBalance(other.getBalance());
        }
        if (other.getPayType() != 0) {
          setPayType(other.getPayType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CreditProto.Credit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CreditProto.Credit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 2;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private long payDate_ ;
      /**
       * <code>int64 payDate = 3;</code>
       */
      public long getPayDate() {
        return payDate_;
      }
      /**
       * <code>int64 payDate = 3;</code>
       */
      public Builder setPayDate(long value) {
        
        payDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 payDate = 3;</code>
       */
      public Builder clearPayDate() {
        
        payDate_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>string orderId = 4;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderId = 4;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 4;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 4;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private CreditProto.BankInfo bankInfoDto_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          CreditProto.BankInfo, CreditProto.BankInfo.Builder, CreditProto.BankInfoOrBuilder> bankInfoDtoBuilder_;
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      public boolean hasBankInfoDto() {
        return bankInfoDtoBuilder_ != null || bankInfoDto_ != null;
      }
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      public CreditProto.BankInfo getBankInfoDto() {
        if (bankInfoDtoBuilder_ == null) {
          return bankInfoDto_ == null ? CreditProto.BankInfo.getDefaultInstance() : bankInfoDto_;
        } else {
          return bankInfoDtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      public Builder setBankInfoDto(CreditProto.BankInfo value) {
        if (bankInfoDtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bankInfoDto_ = value;
          onChanged();
        } else {
          bankInfoDtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      public Builder setBankInfoDto(
          CreditProto.BankInfo.Builder builderForValue) {
        if (bankInfoDtoBuilder_ == null) {
          bankInfoDto_ = builderForValue.build();
          onChanged();
        } else {
          bankInfoDtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      public Builder mergeBankInfoDto(CreditProto.BankInfo value) {
        if (bankInfoDtoBuilder_ == null) {
          if (bankInfoDto_ != null) {
            bankInfoDto_ =
              CreditProto.BankInfo.newBuilder(bankInfoDto_).mergeFrom(value).buildPartial();
          } else {
            bankInfoDto_ = value;
          }
          onChanged();
        } else {
          bankInfoDtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      public Builder clearBankInfoDto() {
        if (bankInfoDtoBuilder_ == null) {
          bankInfoDto_ = null;
          onChanged();
        } else {
          bankInfoDto_ = null;
          bankInfoDtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      public CreditProto.BankInfo.Builder getBankInfoDtoBuilder() {
        
        onChanged();
        return getBankInfoDtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      public CreditProto.BankInfoOrBuilder getBankInfoDtoOrBuilder() {
        if (bankInfoDtoBuilder_ != null) {
          return bankInfoDtoBuilder_.getMessageOrBuilder();
        } else {
          return bankInfoDto_ == null ?
              CreditProto.BankInfo.getDefaultInstance() : bankInfoDto_;
        }
      }
      /**
       * <code>.BankInfo bankInfoDto = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CreditProto.BankInfo, CreditProto.BankInfo.Builder, CreditProto.BankInfoOrBuilder> 
          getBankInfoDtoFieldBuilder() {
        if (bankInfoDtoBuilder_ == null) {
          bankInfoDtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CreditProto.BankInfo, CreditProto.BankInfo.Builder, CreditProto.BankInfoOrBuilder>(
                  getBankInfoDto(),
                  getParentForChildren(),
                  isClean());
          bankInfoDto_ = null;
        }
        return bankInfoDtoBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 6;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private double balance_ ;
      /**
       * <code>double balance = 7;</code>
       */
      public double getBalance() {
        return balance_;
      }
      /**
       * <code>double balance = 7;</code>
       */
      public Builder setBalance(double value) {
        
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double balance = 7;</code>
       */
      public Builder clearBalance() {
        
        balance_ = 0D;
        onChanged();
        return this;
      }

      private int payType_ ;
      /**
       * <code>int32 payType = 8;</code>
       */
      public int getPayType() {
        return payType_;
      }
      /**
       * <code>int32 payType = 8;</code>
       */
      public Builder setPayType(int value) {
        
        payType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 payType = 8;</code>
       */
      public Builder clearPayType() {
        
        payType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Credit)
    }

    // @@protoc_insertion_point(class_scope:Credit)
    private static final CreditProto.Credit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CreditProto.Credit();
    }

    public static CreditProto.Credit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Credit>
        PARSER = new com.google.protobuf.AbstractParser<Credit>() {
      public Credit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Credit(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Credit> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Credit> getParserForType() {
      return PARSER;
    }

    public CreditProto.Credit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BankInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BankInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>int32 bankId = 2;</code>
     */
    int getBankId();
  }
  /**
   * Protobuf type {@code BankInfo}
   */
  public  static final class BankInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BankInfo)
      BankInfoOrBuilder {
    // Use BankInfo.newBuilder() to construct.
    private BankInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BankInfo() {
      token_ = "";
      bankId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BankInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 16: {

              bankId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CreditProto.internal_static_BankInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CreditProto.internal_static_BankInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CreditProto.BankInfo.class, CreditProto.BankInfo.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BANKID_FIELD_NUMBER = 2;
    private int bankId_;
    /**
     * <code>int32 bankId = 2;</code>
     */
    public int getBankId() {
      return bankId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (bankId_ != 0) {
        output.writeInt32(2, bankId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (bankId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bankId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CreditProto.BankInfo)) {
        return super.equals(obj);
      }
      CreditProto.BankInfo other = (CreditProto.BankInfo) obj;

      boolean result = true;
      result = result && getToken()
          .equals(other.getToken());
      result = result && (getBankId()
          == other.getBankId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + BANKID_FIELD_NUMBER;
      hash = (53 * hash) + getBankId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CreditProto.BankInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.BankInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.BankInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.BankInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.BankInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.BankInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.BankInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CreditProto.BankInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CreditProto.BankInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CreditProto.BankInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CreditProto.BankInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CreditProto.BankInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CreditProto.BankInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BankInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BankInfo)
        CreditProto.BankInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CreditProto.internal_static_BankInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CreditProto.internal_static_BankInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CreditProto.BankInfo.class, CreditProto.BankInfo.Builder.class);
      }

      // Construct using CreditProto.BankInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        token_ = "";

        bankId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CreditProto.internal_static_BankInfo_descriptor;
      }

      public CreditProto.BankInfo getDefaultInstanceForType() {
        return CreditProto.BankInfo.getDefaultInstance();
      }

      public CreditProto.BankInfo build() {
        CreditProto.BankInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CreditProto.BankInfo buildPartial() {
        CreditProto.BankInfo result = new CreditProto.BankInfo(this);
        result.token_ = token_;
        result.bankId_ = bankId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CreditProto.BankInfo) {
          return mergeFrom((CreditProto.BankInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CreditProto.BankInfo other) {
        if (other == CreditProto.BankInfo.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getBankId() != 0) {
          setBankId(other.getBankId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CreditProto.BankInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CreditProto.BankInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int bankId_ ;
      /**
       * <code>int32 bankId = 2;</code>
       */
      public int getBankId() {
        return bankId_;
      }
      /**
       * <code>int32 bankId = 2;</code>
       */
      public Builder setBankId(int value) {
        
        bankId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bankId = 2;</code>
       */
      public Builder clearBankId() {
        
        bankId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BankInfo)
    }

    // @@protoc_insertion_point(class_scope:BankInfo)
    private static final CreditProto.BankInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CreditProto.BankInfo();
    }

    public static CreditProto.BankInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BankInfo>
        PARSER = new com.google.protobuf.AbstractParser<BankInfo>() {
      public BankInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BankInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BankInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BankInfo> getParserForType() {
      return PARSER;
    }

    public CreditProto.BankInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreditListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreditList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Credit list = 1;</code>
     */
    java.util.List<CreditProto.Credit> 
        getListList();
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    CreditProto.Credit getList(int index);
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    java.util.List<? extends CreditProto.CreditOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    CreditProto.CreditOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CreditList}
   */
  public  static final class CreditList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CreditList)
      CreditListOrBuilder {
    // Use CreditList.newBuilder() to construct.
    private CreditList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreditList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CreditList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<CreditProto.Credit>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(CreditProto.Credit.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CreditProto.internal_static_CreditList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CreditProto.internal_static_CreditList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CreditProto.CreditList.class, CreditProto.CreditList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<CreditProto.Credit> list_;
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    public java.util.List<CreditProto.Credit> getListList() {
      return list_;
    }
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    public java.util.List<? extends CreditProto.CreditOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    public CreditProto.Credit getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .Credit list = 1;</code>
     */
    public CreditProto.CreditOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CreditProto.CreditList)) {
        return super.equals(obj);
      }
      CreditProto.CreditList other = (CreditProto.CreditList) obj;

      boolean result = true;
      result = result && getListList()
          .equals(other.getListList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CreditProto.CreditList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.CreditList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.CreditList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.CreditList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.CreditList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CreditProto.CreditList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CreditProto.CreditList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CreditProto.CreditList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CreditProto.CreditList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CreditProto.CreditList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CreditProto.CreditList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CreditProto.CreditList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CreditProto.CreditList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreditList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CreditList)
        CreditProto.CreditListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CreditProto.internal_static_CreditList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CreditProto.internal_static_CreditList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CreditProto.CreditList.class, CreditProto.CreditList.Builder.class);
      }

      // Construct using CreditProto.CreditList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CreditProto.internal_static_CreditList_descriptor;
      }

      public CreditProto.CreditList getDefaultInstanceForType() {
        return CreditProto.CreditList.getDefaultInstance();
      }

      public CreditProto.CreditList build() {
        CreditProto.CreditList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CreditProto.CreditList buildPartial() {
        CreditProto.CreditList result = new CreditProto.CreditList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CreditProto.CreditList) {
          return mergeFrom((CreditProto.CreditList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CreditProto.CreditList other) {
        if (other == CreditProto.CreditList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CreditProto.CreditList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CreditProto.CreditList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<CreditProto.Credit> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<CreditProto.Credit>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CreditProto.Credit, CreditProto.Credit.Builder, CreditProto.CreditOrBuilder> listBuilder_;

      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public java.util.List<CreditProto.Credit> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public CreditProto.Credit getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder setList(
          int index, CreditProto.Credit value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder setList(
          int index, CreditProto.Credit.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder addList(CreditProto.Credit value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder addList(
          int index, CreditProto.Credit value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder addList(
          CreditProto.Credit.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder addList(
          int index, CreditProto.Credit.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends CreditProto.Credit> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public CreditProto.Credit.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public CreditProto.CreditOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public java.util.List<? extends CreditProto.CreditOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public CreditProto.Credit.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            CreditProto.Credit.getDefaultInstance());
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public CreditProto.Credit.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, CreditProto.Credit.getDefaultInstance());
      }
      /**
       * <code>repeated .Credit list = 1;</code>
       */
      public java.util.List<CreditProto.Credit.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CreditProto.Credit, CreditProto.Credit.Builder, CreditProto.CreditOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CreditProto.Credit, CreditProto.Credit.Builder, CreditProto.CreditOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CreditList)
    }

    // @@protoc_insertion_point(class_scope:CreditList)
    private static final CreditProto.CreditList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CreditProto.CreditList();
    }

    public static CreditProto.CreditList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreditList>
        PARSER = new com.google.protobuf.AbstractParser<CreditList>() {
      public CreditList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CreditList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreditList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreditList> getParserForType() {
      return PARSER;
    }

    public CreditProto.CreditList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Credit_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Credit_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BankInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BankInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreditList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreditList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CreditProto.proto\"\235\001\n\006Credit\022\n\n\002id\030\001 \001" +
      "(\t\022\016\n\006amount\030\002 \001(\001\022\017\n\007payDate\030\003 \001(\003\022\017\n\007o" +
      "rderId\030\004 \001(\t\022\036\n\013bankInfoDto\030\005 \001(\0132\t.Bank" +
      "Info\022\023\n\013description\030\006 \001(\t\022\017\n\007balance\030\007 \001" +
      "(\001\022\017\n\007payType\030\010 \001(\005\")\n\010BankInfo\022\r\n\005token" +
      "\030\001 \001(\t\022\016\n\006bankId\030\002 \001(\005\"#\n\nCreditList\022\025\n\004" +
      "list\030\001 \003(\0132\007.Creditb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Credit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Credit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Credit_descriptor,
        new java.lang.String[] { "Id", "Amount", "PayDate", "OrderId", "BankInfoDto", "Description", "Balance", "PayType", });
    internal_static_BankInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BankInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BankInfo_descriptor,
        new java.lang.String[] { "Token", "BankId", });
    internal_static_CreditList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreditList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreditList_descriptor,
        new java.lang.String[] { "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
