package ir.ord.application.dto.protoes;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SourcesProto.proto

public final class SourcesProto {
  private SourcesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppSourceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppSource)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appVersion = 1;</code>
     */
    String getAppVersion();
    /**
     * <code>string appVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();

    /**
     * <code>string appVersionCode = 2;</code>
     */
    String getAppVersionCode();
    /**
     * <code>string appVersionCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionCodeBytes();

    /**
     * <code>int32 devicePlatform = 3;</code>
     */
    int getDevicePlatform();

    /**
     * <code>string deviceSDK = 4;</code>
     */
    String getDeviceSDK();
    /**
     * <code>string deviceSDK = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceSDKBytes();

    /**
     * <code>string deviceName = 5;</code>
     */
    String getDeviceName();
    /**
     * <code>string deviceName = 5;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    /**
     * <code>string page = 6;</code>
     */
    String getPage();
    /**
     * <code>string page = 6;</code>
     */
    com.google.protobuf.ByteString
        getPageBytes();

    /**
     * <code>.OrdLocation location = 7;</code>
     */
    boolean hasLocation();
    /**
     * <code>.OrdLocation location = 7;</code>
     */
    AddressProto.OrdLocation getLocation();
    /**
     * <code>.OrdLocation location = 7;</code>
     */
    AddressProto.OrdLocationOrBuilder getLocationOrBuilder();
  }
  /**
   * Protobuf type {@code AppSource}
   */
  public  static final class AppSource extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AppSource)
      AppSourceOrBuilder {
    // Use AppSource.newBuilder() to construct.
    private AppSource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppSource() {
      appVersion_ = "";
      appVersionCode_ = "";
      devicePlatform_ = 0;
      deviceSDK_ = "";
      deviceName_ = "";
      page_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppSource(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              appVersion_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              appVersionCode_ = s;
              break;
            }
            case 24: {

              devicePlatform_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              deviceSDK_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              deviceName_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              page_ = s;
              break;
            }
            case 58: {
              AddressProto.OrdLocation.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(AddressProto.OrdLocation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SourcesProto.internal_static_AppSource_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SourcesProto.internal_static_AppSource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AppSource.class, Builder.class);
    }

    public static final int APPVERSION_FIELD_NUMBER = 1;
    private volatile Object appVersion_;
    /**
     * <code>string appVersion = 1;</code>
     */
    public String getAppVersion() {
      Object ref = appVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string appVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      Object ref = appVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPVERSIONCODE_FIELD_NUMBER = 2;
    private volatile Object appVersionCode_;
    /**
     * <code>string appVersionCode = 2;</code>
     */
    public String getAppVersionCode() {
      Object ref = appVersionCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appVersionCode_ = s;
        return s;
      }
    }
    /**
     * <code>string appVersionCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionCodeBytes() {
      Object ref = appVersionCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appVersionCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEPLATFORM_FIELD_NUMBER = 3;
    private int devicePlatform_;
    /**
     * <code>int32 devicePlatform = 3;</code>
     */
    public int getDevicePlatform() {
      return devicePlatform_;
    }

    public static final int DEVICESDK_FIELD_NUMBER = 4;
    private volatile Object deviceSDK_;
    /**
     * <code>string deviceSDK = 4;</code>
     */
    public String getDeviceSDK() {
      Object ref = deviceSDK_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceSDK_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceSDK = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceSDKBytes() {
      Object ref = deviceSDK_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceSDK_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICENAME_FIELD_NUMBER = 5;
    private volatile Object deviceName_;
    /**
     * <code>string deviceName = 5;</code>
     */
    public String getDeviceName() {
      Object ref = deviceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_FIELD_NUMBER = 6;
    private volatile Object page_;
    /**
     * <code>string page = 6;</code>
     */
    public String getPage() {
      Object ref = page_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        page_ = s;
        return s;
      }
    }
    /**
     * <code>string page = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPageBytes() {
      Object ref = page_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        page_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 7;
    private AddressProto.OrdLocation location_;
    /**
     * <code>.OrdLocation location = 7;</code>
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.OrdLocation location = 7;</code>
     */
    public AddressProto.OrdLocation getLocation() {
      return location_ == null ? AddressProto.OrdLocation.getDefaultInstance() : location_;
    }
    /**
     * <code>.OrdLocation location = 7;</code>
     */
    public AddressProto.OrdLocationOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appVersion_);
      }
      if (!getAppVersionCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appVersionCode_);
      }
      if (devicePlatform_ != 0) {
        output.writeInt32(3, devicePlatform_);
      }
      if (!getDeviceSDKBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceSDK_);
      }
      if (!getDeviceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceName_);
      }
      if (!getPageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, page_);
      }
      if (location_ != null) {
        output.writeMessage(7, getLocation());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appVersion_);
      }
      if (!getAppVersionCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appVersionCode_);
      }
      if (devicePlatform_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, devicePlatform_);
      }
      if (!getDeviceSDKBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceSDK_);
      }
      if (!getDeviceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceName_);
      }
      if (!getPageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, page_);
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getLocation());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AppSource)) {
        return super.equals(obj);
      }
      AppSource other = (AppSource) obj;

      boolean result = true;
      result = result && getAppVersion()
          .equals(other.getAppVersion());
      result = result && getAppVersionCode()
          .equals(other.getAppVersionCode());
      result = result && (getDevicePlatform()
          == other.getDevicePlatform());
      result = result && getDeviceSDK()
          .equals(other.getDeviceSDK());
      result = result && getDeviceName()
          .equals(other.getDeviceName());
      result = result && getPage()
          .equals(other.getPage());
      result = result && (hasLocation() == other.hasLocation());
      if (hasLocation()) {
        result = result && getLocation()
            .equals(other.getLocation());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersion().hashCode();
      hash = (37 * hash) + APPVERSIONCODE_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersionCode().hashCode();
      hash = (37 * hash) + DEVICEPLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getDevicePlatform();
      hash = (37 * hash) + DEVICESDK_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceSDK().hashCode();
      hash = (37 * hash) + DEVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceName().hashCode();
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage().hashCode();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AppSource parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppSource parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppSource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppSource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppSource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppSource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppSource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppSource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppSource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AppSource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppSource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppSource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AppSource prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppSource}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppSource)
        AppSourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SourcesProto.internal_static_AppSource_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SourcesProto.internal_static_AppSource_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AppSource.class, Builder.class);
      }

      // Construct using SourcesProto.AppSource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appVersion_ = "";

        appVersionCode_ = "";

        devicePlatform_ = 0;

        deviceSDK_ = "";

        deviceName_ = "";

        page_ = "";

        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SourcesProto.internal_static_AppSource_descriptor;
      }

      public AppSource getDefaultInstanceForType() {
        return AppSource.getDefaultInstance();
      }

      public AppSource build() {
        AppSource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AppSource buildPartial() {
        AppSource result = new AppSource(this);
        result.appVersion_ = appVersion_;
        result.appVersionCode_ = appVersionCode_;
        result.devicePlatform_ = devicePlatform_;
        result.deviceSDK_ = deviceSDK_;
        result.deviceName_ = deviceName_;
        result.page_ = page_;
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AppSource) {
          return mergeFrom((AppSource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AppSource other) {
        if (other == AppSource.getDefaultInstance()) return this;
        if (!other.getAppVersion().isEmpty()) {
          appVersion_ = other.appVersion_;
          onChanged();
        }
        if (!other.getAppVersionCode().isEmpty()) {
          appVersionCode_ = other.appVersionCode_;
          onChanged();
        }
        if (other.getDevicePlatform() != 0) {
          setDevicePlatform(other.getDevicePlatform());
        }
        if (!other.getDeviceSDK().isEmpty()) {
          deviceSDK_ = other.deviceSDK_;
          onChanged();
        }
        if (!other.getDeviceName().isEmpty()) {
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (!other.getPage().isEmpty()) {
          page_ = other.page_;
          onChanged();
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AppSource parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AppSource) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object appVersion_ = "";
      /**
       * <code>string appVersion = 1;</code>
       */
      public String getAppVersion() {
        Object ref = appVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string appVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        Object ref = appVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appVersion = 1;</code>
       */
      public Builder setAppVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appVersion = 1;</code>
       */
      public Builder clearAppVersion() {
        
        appVersion_ = getDefaultInstance().getAppVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string appVersion = 1;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVersion_ = value;
        onChanged();
        return this;
      }

      private Object appVersionCode_ = "";
      /**
       * <code>string appVersionCode = 2;</code>
       */
      public String getAppVersionCode() {
        Object ref = appVersionCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appVersionCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string appVersionCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionCodeBytes() {
        Object ref = appVersionCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appVersionCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appVersionCode = 2;</code>
       */
      public Builder setAppVersionCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVersionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appVersionCode = 2;</code>
       */
      public Builder clearAppVersionCode() {
        
        appVersionCode_ = getDefaultInstance().getAppVersionCode();
        onChanged();
        return this;
      }
      /**
       * <code>string appVersionCode = 2;</code>
       */
      public Builder setAppVersionCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVersionCode_ = value;
        onChanged();
        return this;
      }

      private int devicePlatform_ ;
      /**
       * <code>int32 devicePlatform = 3;</code>
       */
      public int getDevicePlatform() {
        return devicePlatform_;
      }
      /**
       * <code>int32 devicePlatform = 3;</code>
       */
      public Builder setDevicePlatform(int value) {
        
        devicePlatform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 devicePlatform = 3;</code>
       */
      public Builder clearDevicePlatform() {
        
        devicePlatform_ = 0;
        onChanged();
        return this;
      }

      private Object deviceSDK_ = "";
      /**
       * <code>string deviceSDK = 4;</code>
       */
      public String getDeviceSDK() {
        Object ref = deviceSDK_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceSDK_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceSDK = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceSDKBytes() {
        Object ref = deviceSDK_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceSDK_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceSDK = 4;</code>
       */
      public Builder setDeviceSDK(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceSDK_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceSDK = 4;</code>
       */
      public Builder clearDeviceSDK() {
        
        deviceSDK_ = getDefaultInstance().getDeviceSDK();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceSDK = 4;</code>
       */
      public Builder setDeviceSDKBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceSDK_ = value;
        onChanged();
        return this;
      }

      private Object deviceName_ = "";
      /**
       * <code>string deviceName = 5;</code>
       */
      public String getDeviceName() {
        Object ref = deviceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceName = 5;</code>
       */
      public Builder setDeviceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceName = 5;</code>
       */
      public Builder clearDeviceName() {
        
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceName = 5;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceName_ = value;
        onChanged();
        return this;
      }

      private Object page_ = "";
      /**
       * <code>string page = 6;</code>
       */
      public String getPage() {
        Object ref = page_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          page_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string page = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPageBytes() {
        Object ref = page_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          page_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string page = 6;</code>
       */
      public Builder setPage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string page = 6;</code>
       */
      public Builder clearPage() {
        
        page_ = getDefaultInstance().getPage();
        onChanged();
        return this;
      }
      /**
       * <code>string page = 6;</code>
       */
      public Builder setPageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        page_ = value;
        onChanged();
        return this;
      }

      private AddressProto.OrdLocation location_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          AddressProto.OrdLocation, AddressProto.OrdLocation.Builder, AddressProto.OrdLocationOrBuilder> locationBuilder_;
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      public AddressProto.OrdLocation getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? AddressProto.OrdLocation.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      public Builder setLocation(AddressProto.OrdLocation value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      public Builder setLocation(
          AddressProto.OrdLocation.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      public Builder mergeLocation(AddressProto.OrdLocation value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              AddressProto.OrdLocation.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      public AddressProto.OrdLocation.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      public AddressProto.OrdLocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              AddressProto.OrdLocation.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.OrdLocation location = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          AddressProto.OrdLocation, AddressProto.OrdLocation.Builder, AddressProto.OrdLocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              AddressProto.OrdLocation, AddressProto.OrdLocation.Builder, AddressProto.OrdLocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AppSource)
    }

    // @@protoc_insertion_point(class_scope:AppSource)
    private static final AppSource DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AppSource();
    }

    public static AppSource getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppSource>
        PARSER = new com.google.protobuf.AbstractParser<AppSource>() {
      public AppSource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppSource(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppSource> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppSource> getParserForType() {
      return PARSER;
    }

    public AppSource getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WebSourceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WebSource)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string url = 1;</code>
     */
    String getUrl();
    /**
     * <code>string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>string ip = 2;</code>
     */
    String getIp();
    /**
     * <code>string ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>.OrdLocation location = 4;</code>
     */
    boolean hasLocation();
    /**
     * <code>.OrdLocation location = 4;</code>
     */
    AddressProto.OrdLocation getLocation();
    /**
     * <code>.OrdLocation location = 4;</code>
     */
    AddressProto.OrdLocationOrBuilder getLocationOrBuilder();
  }
  /**
   * Protobuf type {@code WebSource}
   */
  public  static final class WebSource extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WebSource)
      WebSourceOrBuilder {
    // Use WebSource.newBuilder() to construct.
    private WebSource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebSource() {
      url_ = "";
      ip_ = "";
      time_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WebSource(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 24: {

              time_ = input.readInt64();
              break;
            }
            case 34: {
              AddressProto.OrdLocation.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(AddressProto.OrdLocation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SourcesProto.internal_static_WebSource_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SourcesProto.internal_static_WebSource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WebSource.class, Builder.class);
    }

    public static final int URL_FIELD_NUMBER = 1;
    private volatile Object url_;
    /**
     * <code>string url = 1;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile Object ip_;
    /**
     * <code>string ip = 2;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>int64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int LOCATION_FIELD_NUMBER = 4;
    private AddressProto.OrdLocation location_;
    /**
     * <code>.OrdLocation location = 4;</code>
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.OrdLocation location = 4;</code>
     */
    public AddressProto.OrdLocation getLocation() {
      return location_ == null ? AddressProto.OrdLocation.getDefaultInstance() : location_;
    }
    /**
     * <code>.OrdLocation location = 4;</code>
     */
    public AddressProto.OrdLocationOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (time_ != 0L) {
        output.writeInt64(3, time_);
      }
      if (location_ != null) {
        output.writeMessage(4, getLocation());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLocation());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof WebSource)) {
        return super.equals(obj);
      }
      WebSource other = (WebSource) obj;

      boolean result = true;
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && getIp()
          .equals(other.getIp());
      result = result && (getTime()
          == other.getTime());
      result = result && (hasLocation() == other.hasLocation());
      if (hasLocation()) {
        result = result && getLocation()
            .equals(other.getLocation());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static WebSource parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebSource parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebSource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebSource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebSource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebSource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebSource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WebSource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static WebSource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static WebSource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static WebSource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WebSource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(WebSource prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WebSource}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WebSource)
        WebSourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SourcesProto.internal_static_WebSource_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SourcesProto.internal_static_WebSource_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WebSource.class, Builder.class);
      }

      // Construct using SourcesProto.WebSource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        url_ = "";

        ip_ = "";

        time_ = 0L;

        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SourcesProto.internal_static_WebSource_descriptor;
      }

      public WebSource getDefaultInstanceForType() {
        return WebSource.getDefaultInstance();
      }

      public WebSource build() {
        WebSource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WebSource buildPartial() {
        WebSource result = new WebSource(this);
        result.url_ = url_;
        result.ip_ = ip_;
        result.time_ = time_;
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WebSource) {
          return mergeFrom((WebSource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WebSource other) {
        if (other == WebSource.getDefaultInstance()) return this;
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WebSource parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WebSource) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object url_ = "";
      /**
       * <code>string url = 1;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 1;</code>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 1;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>string ip = 2;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 3;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private AddressProto.OrdLocation location_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          AddressProto.OrdLocation, AddressProto.OrdLocation.Builder, AddressProto.OrdLocationOrBuilder> locationBuilder_;
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      public AddressProto.OrdLocation getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? AddressProto.OrdLocation.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      public Builder setLocation(AddressProto.OrdLocation value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      public Builder setLocation(
          AddressProto.OrdLocation.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      public Builder mergeLocation(AddressProto.OrdLocation value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              AddressProto.OrdLocation.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      public AddressProto.OrdLocation.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      public AddressProto.OrdLocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              AddressProto.OrdLocation.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.OrdLocation location = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          AddressProto.OrdLocation, AddressProto.OrdLocation.Builder, AddressProto.OrdLocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              AddressProto.OrdLocation, AddressProto.OrdLocation.Builder, AddressProto.OrdLocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:WebSource)
    }

    // @@protoc_insertion_point(class_scope:WebSource)
    private static final WebSource DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new WebSource();
    }

    public static WebSource getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebSource>
        PARSER = new com.google.protobuf.AbstractParser<WebSource>() {
      public WebSource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WebSource(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WebSource> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<WebSource> getParserForType() {
      return PARSER;
    }

    public WebSource getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ButtonSourceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ButtonSource)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string buttonVersion = 1;</code>
     */
    String getButtonVersion();
    /**
     * <code>string buttonVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getButtonVersionBytes();

    /**
     * <code>string ip = 2;</code>
     */
    String getIp();
    /**
     * <code>string ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>string funcKey = 3;</code>
     */
    String getFuncKey();
    /**
     * <code>string funcKey = 3;</code>
     */
    com.google.protobuf.ByteString
        getFuncKeyBytes();

    /**
     * <code>.OrdButton ordButton = 4;</code>
     */
    boolean hasOrdButton();
    /**
     * <code>.OrdButton ordButton = 4;</code>
     */
    ButtonProto.OrdButton getOrdButton();
    /**
     * <code>.OrdButton ordButton = 4;</code>
     */
    ButtonProto.OrdButtonOrBuilder getOrdButtonOrBuilder();
  }
  /**
   * Protobuf type {@code ButtonSource}
   */
  public  static final class ButtonSource extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ButtonSource)
      ButtonSourceOrBuilder {
    // Use ButtonSource.newBuilder() to construct.
    private ButtonSource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ButtonSource() {
      buttonVersion_ = "";
      ip_ = "";
      funcKey_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ButtonSource(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              buttonVersion_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              funcKey_ = s;
              break;
            }
            case 34: {
              ButtonProto.OrdButton.Builder subBuilder = null;
              if (ordButton_ != null) {
                subBuilder = ordButton_.toBuilder();
              }
              ordButton_ = input.readMessage(ButtonProto.OrdButton.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ordButton_);
                ordButton_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SourcesProto.internal_static_ButtonSource_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SourcesProto.internal_static_ButtonSource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ButtonSource.class, Builder.class);
    }

    public static final int BUTTONVERSION_FIELD_NUMBER = 1;
    private volatile Object buttonVersion_;
    /**
     * <code>string buttonVersion = 1;</code>
     */
    public String getButtonVersion() {
      Object ref = buttonVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        buttonVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string buttonVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getButtonVersionBytes() {
      Object ref = buttonVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        buttonVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile Object ip_;
    /**
     * <code>string ip = 2;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCKEY_FIELD_NUMBER = 3;
    private volatile Object funcKey_;
    /**
     * <code>string funcKey = 3;</code>
     */
    public String getFuncKey() {
      Object ref = funcKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        funcKey_ = s;
        return s;
      }
    }
    /**
     * <code>string funcKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFuncKeyBytes() {
      Object ref = funcKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        funcKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDBUTTON_FIELD_NUMBER = 4;
    private ButtonProto.OrdButton ordButton_;
    /**
     * <code>.OrdButton ordButton = 4;</code>
     */
    public boolean hasOrdButton() {
      return ordButton_ != null;
    }
    /**
     * <code>.OrdButton ordButton = 4;</code>
     */
    public ButtonProto.OrdButton getOrdButton() {
      return ordButton_ == null ? ButtonProto.OrdButton.getDefaultInstance() : ordButton_;
    }
    /**
     * <code>.OrdButton ordButton = 4;</code>
     */
    public ButtonProto.OrdButtonOrBuilder getOrdButtonOrBuilder() {
      return getOrdButton();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getButtonVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buttonVersion_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (!getFuncKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, funcKey_);
      }
      if (ordButton_ != null) {
        output.writeMessage(4, getOrdButton());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getButtonVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buttonVersion_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (!getFuncKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, funcKey_);
      }
      if (ordButton_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getOrdButton());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ButtonSource)) {
        return super.equals(obj);
      }
      ButtonSource other = (ButtonSource) obj;

      boolean result = true;
      result = result && getButtonVersion()
          .equals(other.getButtonVersion());
      result = result && getIp()
          .equals(other.getIp());
      result = result && getFuncKey()
          .equals(other.getFuncKey());
      result = result && (hasOrdButton() == other.hasOrdButton());
      if (hasOrdButton()) {
        result = result && getOrdButton()
            .equals(other.getOrdButton());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUTTONVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getButtonVersion().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + FUNCKEY_FIELD_NUMBER;
      hash = (53 * hash) + getFuncKey().hashCode();
      if (hasOrdButton()) {
        hash = (37 * hash) + ORDBUTTON_FIELD_NUMBER;
        hash = (53 * hash) + getOrdButton().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ButtonSource parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ButtonSource parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ButtonSource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ButtonSource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ButtonSource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ButtonSource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ButtonSource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ButtonSource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ButtonSource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ButtonSource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ButtonSource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ButtonSource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ButtonSource prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ButtonSource}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ButtonSource)
        ButtonSourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SourcesProto.internal_static_ButtonSource_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SourcesProto.internal_static_ButtonSource_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ButtonSource.class, Builder.class);
      }

      // Construct using SourcesProto.ButtonSource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        buttonVersion_ = "";

        ip_ = "";

        funcKey_ = "";

        if (ordButtonBuilder_ == null) {
          ordButton_ = null;
        } else {
          ordButton_ = null;
          ordButtonBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SourcesProto.internal_static_ButtonSource_descriptor;
      }

      public ButtonSource getDefaultInstanceForType() {
        return ButtonSource.getDefaultInstance();
      }

      public ButtonSource build() {
        ButtonSource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ButtonSource buildPartial() {
        ButtonSource result = new ButtonSource(this);
        result.buttonVersion_ = buttonVersion_;
        result.ip_ = ip_;
        result.funcKey_ = funcKey_;
        if (ordButtonBuilder_ == null) {
          result.ordButton_ = ordButton_;
        } else {
          result.ordButton_ = ordButtonBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ButtonSource) {
          return mergeFrom((ButtonSource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ButtonSource other) {
        if (other == ButtonSource.getDefaultInstance()) return this;
        if (!other.getButtonVersion().isEmpty()) {
          buttonVersion_ = other.buttonVersion_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getFuncKey().isEmpty()) {
          funcKey_ = other.funcKey_;
          onChanged();
        }
        if (other.hasOrdButton()) {
          mergeOrdButton(other.getOrdButton());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ButtonSource parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ButtonSource) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object buttonVersion_ = "";
      /**
       * <code>string buttonVersion = 1;</code>
       */
      public String getButtonVersion() {
        Object ref = buttonVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          buttonVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string buttonVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getButtonVersionBytes() {
        Object ref = buttonVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          buttonVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string buttonVersion = 1;</code>
       */
      public Builder setButtonVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buttonVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string buttonVersion = 1;</code>
       */
      public Builder clearButtonVersion() {
        
        buttonVersion_ = getDefaultInstance().getButtonVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string buttonVersion = 1;</code>
       */
      public Builder setButtonVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buttonVersion_ = value;
        onChanged();
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>string ip = 2;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private Object funcKey_ = "";
      /**
       * <code>string funcKey = 3;</code>
       */
      public String getFuncKey() {
        Object ref = funcKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          funcKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string funcKey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFuncKeyBytes() {
        Object ref = funcKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          funcKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string funcKey = 3;</code>
       */
      public Builder setFuncKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        funcKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string funcKey = 3;</code>
       */
      public Builder clearFuncKey() {
        
        funcKey_ = getDefaultInstance().getFuncKey();
        onChanged();
        return this;
      }
      /**
       * <code>string funcKey = 3;</code>
       */
      public Builder setFuncKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        funcKey_ = value;
        onChanged();
        return this;
      }

      private ButtonProto.OrdButton ordButton_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ButtonProto.OrdButton, ButtonProto.OrdButton.Builder, ButtonProto.OrdButtonOrBuilder> ordButtonBuilder_;
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      public boolean hasOrdButton() {
        return ordButtonBuilder_ != null || ordButton_ != null;
      }
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      public ButtonProto.OrdButton getOrdButton() {
        if (ordButtonBuilder_ == null) {
          return ordButton_ == null ? ButtonProto.OrdButton.getDefaultInstance() : ordButton_;
        } else {
          return ordButtonBuilder_.getMessage();
        }
      }
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      public Builder setOrdButton(ButtonProto.OrdButton value) {
        if (ordButtonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ordButton_ = value;
          onChanged();
        } else {
          ordButtonBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      public Builder setOrdButton(
          ButtonProto.OrdButton.Builder builderForValue) {
        if (ordButtonBuilder_ == null) {
          ordButton_ = builderForValue.build();
          onChanged();
        } else {
          ordButtonBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      public Builder mergeOrdButton(ButtonProto.OrdButton value) {
        if (ordButtonBuilder_ == null) {
          if (ordButton_ != null) {
            ordButton_ =
              ButtonProto.OrdButton.newBuilder(ordButton_).mergeFrom(value).buildPartial();
          } else {
            ordButton_ = value;
          }
          onChanged();
        } else {
          ordButtonBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      public Builder clearOrdButton() {
        if (ordButtonBuilder_ == null) {
          ordButton_ = null;
          onChanged();
        } else {
          ordButton_ = null;
          ordButtonBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      public ButtonProto.OrdButton.Builder getOrdButtonBuilder() {
        
        onChanged();
        return getOrdButtonFieldBuilder().getBuilder();
      }
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      public ButtonProto.OrdButtonOrBuilder getOrdButtonOrBuilder() {
        if (ordButtonBuilder_ != null) {
          return ordButtonBuilder_.getMessageOrBuilder();
        } else {
          return ordButton_ == null ?
              ButtonProto.OrdButton.getDefaultInstance() : ordButton_;
        }
      }
      /**
       * <code>.OrdButton ordButton = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ButtonProto.OrdButton, ButtonProto.OrdButton.Builder, ButtonProto.OrdButtonOrBuilder> 
          getOrdButtonFieldBuilder() {
        if (ordButtonBuilder_ == null) {
          ordButtonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ButtonProto.OrdButton, ButtonProto.OrdButton.Builder, ButtonProto.OrdButtonOrBuilder>(
                  getOrdButton(),
                  getParentForChildren(),
                  isClean());
          ordButton_ = null;
        }
        return ordButtonBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ButtonSource)
    }

    // @@protoc_insertion_point(class_scope:ButtonSource)
    private static final ButtonSource DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ButtonSource();
    }

    public static ButtonSource getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ButtonSource>
        PARSER = new com.google.protobuf.AbstractParser<ButtonSource>() {
      public ButtonSource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ButtonSource(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ButtonSource> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ButtonSource> getParserForType() {
      return PARSER;
    }

    public ButtonSource getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppSource_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppSource_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebSource_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebSource_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ButtonSource_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ButtonSource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022SourcesProto.proto\032\022AddressProto.proto" +
      "\032\021ButtonProto.proto\"\244\001\n\tAppSource\022\022\n\napp" +
      "Version\030\001 \001(\t\022\026\n\016appVersionCode\030\002 \001(\t\022\026\n" +
      "\016devicePlatform\030\003 \001(\005\022\021\n\tdeviceSDK\030\004 \001(\t" +
      "\022\022\n\ndeviceName\030\005 \001(\t\022\014\n\004page\030\006 \001(\t\022\036\n\010lo" +
      "cation\030\007 \001(\0132\014.OrdLocation\"R\n\tWebSource\022" +
      "\013\n\003url\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\022\014\n\004time\030\003 \001(\003\022\036" +
      "\n\010location\030\004 \001(\0132\014.OrdLocation\"a\n\014Button" +
      "Source\022\025\n\rbuttonVersion\030\001 \001(\t\022\n\n\002ip\030\002 \001(" +
      "\t\022\017\n\007funcKey\030\003 \001(\t\022\035\n\tordButton\030\004 \001(\0132\n.",
      "OrdButtonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AddressProto.getDescriptor(),
          ButtonProto.getDescriptor(),
        }, assigner);
    internal_static_AppSource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AppSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppSource_descriptor,
        new String[] { "AppVersion", "AppVersionCode", "DevicePlatform", "DeviceSDK", "DeviceName", "Page", "Location", });
    internal_static_WebSource_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WebSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebSource_descriptor,
        new String[] { "Url", "Ip", "Time", "Location", });
    internal_static_ButtonSource_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ButtonSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ButtonSource_descriptor,
        new String[] { "ButtonVersion", "Ip", "FuncKey", "OrdButton", });
    AddressProto.getDescriptor();
    ButtonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
