package ir.ord.application.dto.protoes;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimePeriodObjectProto.proto


public final class TimePeriodObjectProto {
  private TimePeriodObjectProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimePeriodObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TimePeriodObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timeStamp = 1;</code>
     */
    long getTimeStamp();

    /**
     * <code>.TimePeriodService timePeriodDto = 2;</code>
     */
    boolean hasTimePeriodDto();
    /**
     * <code>.TimePeriodService timePeriodDto = 2;</code>
     */
    TimePeriodProto.TimePeriod getTimePeriodDto();
    /**
     * <code>.TimePeriodService timePeriodDto = 2;</code>
     */
    TimePeriodProto.TimePeriodOrBuilder getTimePeriodDtoOrBuilder();

    /**
     * <code>string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string actor = 4;</code>
     */
    java.lang.String getActor();
    /**
     * <code>string actor = 4;</code>
     */
    com.google.protobuf.ByteString
        getActorBytes();

    /**
     * <code>int64 date = 5;</code>
     */
    long getDate();
  }
  /**
   * Protobuf type {@code TimePeriodObject}
   */
  public  static final class TimePeriodObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TimePeriodObject)
      TimePeriodObjectOrBuilder {
    // Use TimePeriodObject.newBuilder() to construct.
    private TimePeriodObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimePeriodObject() {
      timeStamp_ = 0L;
      description_ = "";
      actor_ = "";
      date_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TimePeriodObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timeStamp_ = input.readInt64();
              break;
            }
            case 18: {
              TimePeriodProto.TimePeriod.Builder subBuilder = null;
              if (timePeriodDto_ != null) {
                subBuilder = timePeriodDto_.toBuilder();
              }
              timePeriodDto_ = input.readMessage(TimePeriodProto.TimePeriod.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timePeriodDto_);
                timePeriodDto_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              actor_ = s;
              break;
            }
            case 40: {

              date_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TimePeriodObjectProto.internal_static_TimePeriodObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TimePeriodObjectProto.internal_static_TimePeriodObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TimePeriodObjectProto.TimePeriodObject.class, TimePeriodObjectProto.TimePeriodObject.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timeStamp_;
    /**
     * <code>int64 timeStamp = 1;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int TIMEPERIODDTO_FIELD_NUMBER = 2;
    private TimePeriodProto.TimePeriod timePeriodDto_;
    /**
     * <code>.TimePeriodService timePeriodDto = 2;</code>
     */
    public boolean hasTimePeriodDto() {
      return timePeriodDto_ != null;
    }
    /**
     * <code>.TimePeriodService timePeriodDto = 2;</code>
     */
    public TimePeriodProto.TimePeriod getTimePeriodDto() {
      return timePeriodDto_ == null ? TimePeriodProto.TimePeriod.getDefaultInstance() : timePeriodDto_;
    }
    /**
     * <code>.TimePeriodService timePeriodDto = 2;</code>
     */
    public TimePeriodProto.TimePeriodOrBuilder getTimePeriodDtoOrBuilder() {
      return getTimePeriodDto();
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTOR_FIELD_NUMBER = 4;
    private volatile java.lang.Object actor_;
    /**
     * <code>string actor = 4;</code>
     */
    public java.lang.String getActor() {
      java.lang.Object ref = actor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actor_ = s;
        return s;
      }
    }
    /**
     * <code>string actor = 4;</code>
     */
    public com.google.protobuf.ByteString
        getActorBytes() {
      java.lang.Object ref = actor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 5;
    private long date_;
    /**
     * <code>int64 date = 5;</code>
     */
    public long getDate() {
      return date_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timeStamp_ != 0L) {
        output.writeInt64(1, timeStamp_);
      }
      if (timePeriodDto_ != null) {
        output.writeMessage(2, getTimePeriodDto());
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (!getActorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, actor_);
      }
      if (date_ != 0L) {
        output.writeInt64(5, date_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timeStamp_);
      }
      if (timePeriodDto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTimePeriodDto());
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (!getActorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, actor_);
      }
      if (date_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, date_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TimePeriodObjectProto.TimePeriodObject)) {
        return super.equals(obj);
      }
      TimePeriodObjectProto.TimePeriodObject other = (TimePeriodObjectProto.TimePeriodObject) obj;

      boolean result = true;
      result = result && (getTimeStamp()
          == other.getTimeStamp());
      result = result && (hasTimePeriodDto() == other.hasTimePeriodDto());
      if (hasTimePeriodDto()) {
        result = result && getTimePeriodDto()
            .equals(other.getTimePeriodDto());
      }
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getActor()
          .equals(other.getActor());
      result = result && (getDate()
          == other.getDate());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      if (hasTimePeriodDto()) {
        hash = (37 * hash) + TIMEPERIODDTO_FIELD_NUMBER;
        hash = (53 * hash) + getTimePeriodDto().hashCode();
      }
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + ACTOR_FIELD_NUMBER;
      hash = (53 * hash) + getActor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TimePeriodObjectProto.TimePeriodObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimePeriodObjectProto.TimePeriodObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TimePeriodObjectProto.TimePeriodObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TimePeriodObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TimePeriodObject)
        TimePeriodObjectProto.TimePeriodObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TimePeriodObjectProto.internal_static_TimePeriodObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TimePeriodObjectProto.internal_static_TimePeriodObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TimePeriodObjectProto.TimePeriodObject.class, TimePeriodObjectProto.TimePeriodObject.Builder.class);
      }

      // Construct using TimePeriodObjectProto.TimePeriodObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timeStamp_ = 0L;

        if (timePeriodDtoBuilder_ == null) {
          timePeriodDto_ = null;
        } else {
          timePeriodDto_ = null;
          timePeriodDtoBuilder_ = null;
        }
        description_ = "";

        actor_ = "";

        date_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TimePeriodObjectProto.internal_static_TimePeriodObject_descriptor;
      }

      public TimePeriodObjectProto.TimePeriodObject getDefaultInstanceForType() {
        return TimePeriodObjectProto.TimePeriodObject.getDefaultInstance();
      }

      public TimePeriodObjectProto.TimePeriodObject build() {
        TimePeriodObjectProto.TimePeriodObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TimePeriodObjectProto.TimePeriodObject buildPartial() {
        TimePeriodObjectProto.TimePeriodObject result = new TimePeriodObjectProto.TimePeriodObject(this);
        result.timeStamp_ = timeStamp_;
        if (timePeriodDtoBuilder_ == null) {
          result.timePeriodDto_ = timePeriodDto_;
        } else {
          result.timePeriodDto_ = timePeriodDtoBuilder_.build();
        }
        result.description_ = description_;
        result.actor_ = actor_;
        result.date_ = date_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TimePeriodObjectProto.TimePeriodObject) {
          return mergeFrom((TimePeriodObjectProto.TimePeriodObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TimePeriodObjectProto.TimePeriodObject other) {
        if (other == TimePeriodObjectProto.TimePeriodObject.getDefaultInstance()) return this;
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasTimePeriodDto()) {
          mergeTimePeriodDto(other.getTimePeriodDto());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getActor().isEmpty()) {
          actor_ = other.actor_;
          onChanged();
        }
        if (other.getDate() != 0L) {
          setDate(other.getDate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TimePeriodObjectProto.TimePeriodObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TimePeriodObjectProto.TimePeriodObject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>int64 timeStamp = 1;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>int64 timeStamp = 1;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timeStamp = 1;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private TimePeriodProto.TimePeriod timePeriodDto_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TimePeriodProto.TimePeriod, TimePeriodProto.TimePeriod.Builder, TimePeriodProto.TimePeriodOrBuilder> timePeriodDtoBuilder_;
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      public boolean hasTimePeriodDto() {
        return timePeriodDtoBuilder_ != null || timePeriodDto_ != null;
      }
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      public TimePeriodProto.TimePeriod getTimePeriodDto() {
        if (timePeriodDtoBuilder_ == null) {
          return timePeriodDto_ == null ? TimePeriodProto.TimePeriod.getDefaultInstance() : timePeriodDto_;
        } else {
          return timePeriodDtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      public Builder setTimePeriodDto(TimePeriodProto.TimePeriod value) {
        if (timePeriodDtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timePeriodDto_ = value;
          onChanged();
        } else {
          timePeriodDtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      public Builder setTimePeriodDto(
          TimePeriodProto.TimePeriod.Builder builderForValue) {
        if (timePeriodDtoBuilder_ == null) {
          timePeriodDto_ = builderForValue.build();
          onChanged();
        } else {
          timePeriodDtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      public Builder mergeTimePeriodDto(TimePeriodProto.TimePeriod value) {
        if (timePeriodDtoBuilder_ == null) {
          if (timePeriodDto_ != null) {
            timePeriodDto_ =
              TimePeriodProto.TimePeriod.newBuilder(timePeriodDto_).mergeFrom(value).buildPartial();
          } else {
            timePeriodDto_ = value;
          }
          onChanged();
        } else {
          timePeriodDtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      public Builder clearTimePeriodDto() {
        if (timePeriodDtoBuilder_ == null) {
          timePeriodDto_ = null;
          onChanged();
        } else {
          timePeriodDto_ = null;
          timePeriodDtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      public TimePeriodProto.TimePeriod.Builder getTimePeriodDtoBuilder() {
        
        onChanged();
        return getTimePeriodDtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      public TimePeriodProto.TimePeriodOrBuilder getTimePeriodDtoOrBuilder() {
        if (timePeriodDtoBuilder_ != null) {
          return timePeriodDtoBuilder_.getMessageOrBuilder();
        } else {
          return timePeriodDto_ == null ?
              TimePeriodProto.TimePeriod.getDefaultInstance() : timePeriodDto_;
        }
      }
      /**
       * <code>.TimePeriodService timePeriodDto = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TimePeriodProto.TimePeriod, TimePeriodProto.TimePeriod.Builder, TimePeriodProto.TimePeriodOrBuilder>
          getTimePeriodDtoFieldBuilder() {
        if (timePeriodDtoBuilder_ == null) {
          timePeriodDtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TimePeriodProto.TimePeriod, TimePeriodProto.TimePeriod.Builder, TimePeriodProto.TimePeriodOrBuilder>(
                  getTimePeriodDto(),
                  getParentForChildren(),
                  isClean());
          timePeriodDto_ = null;
        }
        return timePeriodDtoBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object actor_ = "";
      /**
       * <code>string actor = 4;</code>
       */
      public java.lang.String getActor() {
        java.lang.Object ref = actor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          actor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string actor = 4;</code>
       */
      public com.google.protobuf.ByteString
          getActorBytes() {
        java.lang.Object ref = actor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actor = 4;</code>
       */
      public Builder setActor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        actor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string actor = 4;</code>
       */
      public Builder clearActor() {
        
        actor_ = getDefaultInstance().getActor();
        onChanged();
        return this;
      }
      /**
       * <code>string actor = 4;</code>
       */
      public Builder setActorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        actor_ = value;
        onChanged();
        return this;
      }

      private long date_ ;
      /**
       * <code>int64 date = 5;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>int64 date = 5;</code>
       */
      public Builder setDate(long value) {
        
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 date = 5;</code>
       */
      public Builder clearDate() {
        
        date_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TimePeriodObject)
    }

    // @@protoc_insertion_point(class_scope:TimePeriodObject)
    private static final TimePeriodObjectProto.TimePeriodObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TimePeriodObjectProto.TimePeriodObject();
    }

    public static TimePeriodObjectProto.TimePeriodObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimePeriodObject>
        PARSER = new com.google.protobuf.AbstractParser<TimePeriodObject>() {
      public TimePeriodObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TimePeriodObject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimePeriodObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimePeriodObject> getParserForType() {
      return PARSER;
    }

    public TimePeriodObjectProto.TimePeriodObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TimePeriodObjectListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TimePeriodObjectList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    java.util.List<TimePeriodObjectProto.TimePeriodObject> 
        getListList();
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    TimePeriodObjectProto.TimePeriodObject getList(int index);
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    java.util.List<? extends TimePeriodObjectProto.TimePeriodObjectOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    TimePeriodObjectProto.TimePeriodObjectOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TimePeriodObjectList}
   */
  public  static final class TimePeriodObjectList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TimePeriodObjectList)
      TimePeriodObjectListOrBuilder {
    // Use TimePeriodObjectList.newBuilder() to construct.
    private TimePeriodObjectList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimePeriodObjectList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TimePeriodObjectList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<TimePeriodObjectProto.TimePeriodObject>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(TimePeriodObjectProto.TimePeriodObject.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TimePeriodObjectProto.internal_static_TimePeriodObjectList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TimePeriodObjectProto.internal_static_TimePeriodObjectList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TimePeriodObjectProto.TimePeriodObjectList.class, TimePeriodObjectProto.TimePeriodObjectList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<TimePeriodObjectProto.TimePeriodObject> list_;
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    public java.util.List<TimePeriodObjectProto.TimePeriodObject> getListList() {
      return list_;
    }
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    public java.util.List<? extends TimePeriodObjectProto.TimePeriodObjectOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    public TimePeriodObjectProto.TimePeriodObject getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .TimePeriodObject list = 1;</code>
     */
    public TimePeriodObjectProto.TimePeriodObjectOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TimePeriodObjectProto.TimePeriodObjectList)) {
        return super.equals(obj);
      }
      TimePeriodObjectProto.TimePeriodObjectList other = (TimePeriodObjectProto.TimePeriodObjectList) obj;

      boolean result = true;
      result = result && getListList()
          .equals(other.getListList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimePeriodObjectProto.TimePeriodObjectList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TimePeriodObjectProto.TimePeriodObjectList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TimePeriodObjectList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TimePeriodObjectList)
        TimePeriodObjectProto.TimePeriodObjectListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TimePeriodObjectProto.internal_static_TimePeriodObjectList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TimePeriodObjectProto.internal_static_TimePeriodObjectList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TimePeriodObjectProto.TimePeriodObjectList.class, TimePeriodObjectProto.TimePeriodObjectList.Builder.class);
      }

      // Construct using TimePeriodObjectProto.TimePeriodObjectList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TimePeriodObjectProto.internal_static_TimePeriodObjectList_descriptor;
      }

      public TimePeriodObjectProto.TimePeriodObjectList getDefaultInstanceForType() {
        return TimePeriodObjectProto.TimePeriodObjectList.getDefaultInstance();
      }

      public TimePeriodObjectProto.TimePeriodObjectList build() {
        TimePeriodObjectProto.TimePeriodObjectList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TimePeriodObjectProto.TimePeriodObjectList buildPartial() {
        TimePeriodObjectProto.TimePeriodObjectList result = new TimePeriodObjectProto.TimePeriodObjectList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TimePeriodObjectProto.TimePeriodObjectList) {
          return mergeFrom((TimePeriodObjectProto.TimePeriodObjectList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TimePeriodObjectProto.TimePeriodObjectList other) {
        if (other == TimePeriodObjectProto.TimePeriodObjectList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TimePeriodObjectProto.TimePeriodObjectList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TimePeriodObjectProto.TimePeriodObjectList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<TimePeriodObjectProto.TimePeriodObject> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<TimePeriodObjectProto.TimePeriodObject>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          TimePeriodObjectProto.TimePeriodObject, TimePeriodObjectProto.TimePeriodObject.Builder, TimePeriodObjectProto.TimePeriodObjectOrBuilder> listBuilder_;

      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public java.util.List<TimePeriodObjectProto.TimePeriodObject> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public TimePeriodObjectProto.TimePeriodObject getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder setList(
          int index, TimePeriodObjectProto.TimePeriodObject value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder setList(
          int index, TimePeriodObjectProto.TimePeriodObject.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder addList(TimePeriodObjectProto.TimePeriodObject value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder addList(
          int index, TimePeriodObjectProto.TimePeriodObject value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder addList(
          TimePeriodObjectProto.TimePeriodObject.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder addList(
          int index, TimePeriodObjectProto.TimePeriodObject.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends TimePeriodObjectProto.TimePeriodObject> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public TimePeriodObjectProto.TimePeriodObject.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public TimePeriodObjectProto.TimePeriodObjectOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public java.util.List<? extends TimePeriodObjectProto.TimePeriodObjectOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public TimePeriodObjectProto.TimePeriodObject.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            TimePeriodObjectProto.TimePeriodObject.getDefaultInstance());
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public TimePeriodObjectProto.TimePeriodObject.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, TimePeriodObjectProto.TimePeriodObject.getDefaultInstance());
      }
      /**
       * <code>repeated .TimePeriodObject list = 1;</code>
       */
      public java.util.List<TimePeriodObjectProto.TimePeriodObject.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          TimePeriodObjectProto.TimePeriodObject, TimePeriodObjectProto.TimePeriodObject.Builder, TimePeriodObjectProto.TimePeriodObjectOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              TimePeriodObjectProto.TimePeriodObject, TimePeriodObjectProto.TimePeriodObject.Builder, TimePeriodObjectProto.TimePeriodObjectOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TimePeriodObjectList)
    }

    // @@protoc_insertion_point(class_scope:TimePeriodObjectList)
    private static final TimePeriodObjectProto.TimePeriodObjectList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TimePeriodObjectProto.TimePeriodObjectList();
    }

    public static TimePeriodObjectProto.TimePeriodObjectList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimePeriodObjectList>
        PARSER = new com.google.protobuf.AbstractParser<TimePeriodObjectList>() {
      public TimePeriodObjectList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TimePeriodObjectList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimePeriodObjectList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimePeriodObjectList> getParserForType() {
      return PARSER;
    }

    public TimePeriodObjectProto.TimePeriodObjectList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimePeriodObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimePeriodObject_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimePeriodObjectList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimePeriodObjectList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033TimePeriodObjectProto.proto\032\025TimePerio" +
      "dProto.proto\"{\n\020TimePeriodObject\022\021\n\ttime" +
      "Stamp\030\001 \001(\003\022\"\n\rtimePeriodDto\030\002 \001(\0132\013.Tim" +
      "ePeriod\022\023\n\013description\030\003 \001(\t\022\r\n\005actor\030\004 " +
      "\001(\t\022\014\n\004date\030\005 \001(\003\"7\n\024TimePeriodObjectLis" +
      "t\022\037\n\004list\030\001 \003(\0132\021.TimePeriodObjectb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TimePeriodProto.getDescriptor(),
        }, assigner);
    internal_static_TimePeriodObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TimePeriodObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimePeriodObject_descriptor,
        new java.lang.String[] { "TimeStamp", "TimePeriodDto", "Description", "Actor", "Date", });
    internal_static_TimePeriodObjectList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TimePeriodObjectList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimePeriodObjectList_descriptor,
        new java.lang.String[] { "List", });
    TimePeriodProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
