swagger: "2.0"
info:
  title: User API
  description: Move your app forward with the User API
  version: "1.0.0"
# the domain of the service
host: api.filemanager
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
tags:
- name: "UserRegistration"
  description: "every thing about user registration rest api"
- name: "UserProfile"
  description: "every thing about user profile rest api"
produces:
  - application/json
consumes: 
  - application/json
paths:
  /user/register:
    post:
      tags: 
      - "UserRegistration"
      summary: Add a new user
      description: add new user and sms activation code to user mobile number
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              countryCode:
                type: string
              mobileNumber:
                type: string
              deviceId:
                type: string
              deviceModel:
                type: string
              osVersion:
                type: string
              clientType:
                type: string
              clientVersion:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              retryCount: 
                type: integer
              codeLength:
                type: integer
        '500':
          description: Internal Server Error
    put:
      tags: 
      - "UserRegistration"
      summary: change user mobile number
      description: add new user and sms activation code to user mobile number
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              countryCode:
                type: string
              mobileNumber:
                type: string
              deviceId:
                type: string
              deviceModel:
                type: string
              osVersion:
                type: string
              clientType:
                type: string
              clientVersion:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              retryCount: 
                type: integer
              codeLength:
                type: integer
        '500':
          description: Internal Server Error

  /user/register/verify:
    post:
      tags: 
      - "UserRegistration"
      summary: User verification
      description: Verify user using the code generated server-side and sent to him
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              code:
                type: string
              deviceId:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              userId: 
                type: string
              authToken:
                type: string
              registrationState:
                type: string
        '500':
          description: Internal Server Error
  /user/register/resend:
    post:
      tags: 
      - "UserRegistration"
      summary: send code again via sms
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              deviceId:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              retryCount:
                type: integer
              codeLength:
                type: integer
        '500':
          description: Internal Server Error
  /user/register/call:
    post:
      tags: 
      - "UserRegistration"
      summary: send code again via call
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              deviceId:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              retryCount:
                type: integer
              codeLength:
                type: integer
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      tags: 
      - "UserProfile"
      summary: Add user info
      parameters:
        - in: body
          name: data
          required: true
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
        - in: header
          name: auth
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              mobileNumber:
                type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error