package servlets;

import biz.TestDto;
import dal.TestEntity;
import org.modelmapper.ModelMapper;

import javax.servlet.*;
import java.io.IOException;

/**
 * Created by vahid on 8/20/17.
 */
public class ServletTest implements Servlet {
    public void init(ServletConfig servletConfig) throws ServletException {
        System.out.println("servletTest initialized");
    }

    public ServletConfig getServletConfig() {
        return null;
    }

    public void service(ServletRequest servletRequest, ServletResponse servletResponse) throws ServletException, IOException {
//        System.out.println(servletRequest.getContentType());
        servletResponse.setContentType("text/html");

        TestEntity testEntity = new TestEntity();
        testEntity.setCode("code12345");
        testEntity.setValue("value12345");
        testEntity.setId((long) 1000);
        ModelMapper modelMapper = new ModelMapper();
        TestDto testDto = modelMapper.map(testEntity, TestDto.class);
        System.out.println(testDto.toString());
        servletRequest.setAttribute("testDto", testDto);
        servletRequest.setAttribute("isTest", true);
        servletRequest.setAttribute("testValue", "congratulations your test successfully done. " +
                "This generated by servlet and illustrated by JSTL");
        RequestDispatcher requestDispatcher = servletRequest.getRequestDispatcher("pages/test.jsp");
//        ((HttpServletResponse)servletResponse).sendRedirect("pages/servletTest.html");
        requestDispatcher.forward(servletRequest, servletResponse);
    }

    public String getServletInfo() {
        return null;
    }

    public void destroy() {
        System.out.println("destroyed");
    }
}
