package ir.ord.application; /**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import org.apache.thrift.TEnum;

public enum RPCEntityEnum implements TEnum {
  PACKAGE_ENTITY(1),
  CATEGORY_ENTITY(2),
  TIME_PERIOD_ENTITY(3),
  GIFT_ENTITY(4);

  private final int value;

  private RPCEntityEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RPCEntityEnum findByValue(int value) { 
    switch (value) {
      case 1:
        return PACKAGE_ENTITY;
      case 2:
        return CATEGORY_ENTITY;
      case 3:
        return TIME_PERIOD_ENTITY;
      case 4:
        return GIFT_ENTITY;
      default:
        return null;
    }
  }
}
